### ISSUE TITLE
revisions to figure 7, and discussion

### ISSUE THREAD

**Issue by astrorobyn** [gusbeane/actions_systematic#13]
I think it would be useful to add to figure 7 horizontal lines showing the midplane deviation that results in 100% systematic error on J_z for the different orbits considered in the paper, and to list the delta phi / chord length that corresponds to a median range of that value. See revisions just pushed to section (now) 4.1.

**Comment by gusbeane** [comment]
Should be fixed in 85cd729005ccb56467378a9dfebaa2539f429c28, but @astrorobyn double check modifications to the thick-disk discussion
